# Generated by Django 5.2.5 on 2025-09-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name_plural': 'Suppliers'},
        ),
    ]
