# Generated by Django 5.2.5 on 2025-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'brands'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='update_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
