# Generated by Django 5.2.5 on 2025-09-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name_plural': 'Brands'},
        ),
    ]
